spring:
  application:
    name: lekhai
  server:
    port: 8080

# Database Configuration
  datasource:
    name: lekhai
    url: ${DB_URL:jdbc:postgresql://ep-curly-king-a1k58bcv-pooler.ap-southeast-1.aws.neon.tech/neondb}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD:npg_4T6EDcxSzogY}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false

# JWT Configuration
rsa:
  public-key: ${PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnjhG43rKvHWvANMzf1zOQpNywpFifeO1LrLeXXNT4bK06KOZY2HN2MXXs3hXWeT1S1oLBq7HYMkd/KLfd5C+9n0C6W778po+FgiusX9x5lXRdnE6yzXYxhCQySaGB+fJgjN807ErB2OTqbGBsmWFESzxv1fphKy8WwWlY4XvBaTefDsg2EfxfygSxfit2TdKSuBm8M3ZpUV5b/DM1qaaV1dK+QtEXewwtf36Dd/kSK4/K1OhcAaJOtAEivx3UWSZUvOrHCpQra2sCFKcmPmS/xuqOma2V0xiNlADdycDKlbYbg7O6k/4JjTg+4lkP/wK0rBrSijk4wsW7V0w5BXhWQIDAQAB}
  private-key: ${PRIVATE_KEY:MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCeOEbjesq8da8A0zN/XM5Ck3LCkWJ947Uust5dc1PhsrToo5ljYc3YxdezeFdZ5PVLWgsGrsdgyR38ot93kL72fQLpbvvymj4WCK6xf3HmVdF2cTrLNdjGEJDJJoYH58mCM3zTsSsHY5OpsYGyZYURLPG/V+mErLxbBaVjhe8FpN58OyDYR/F/KBLF+K3ZN0pK4GbwzdmlRXlv8MzWpppXV0r5C0Rd7DC1/foN3+RIrj8rU6FwBok60ASK/HdRZJlS86scKlCtrawIUpyY+ZL/G6o6ZrZXTGI2UAN3JwMqVthuDs7qT/gmNOD7iWQ//ArSsGtKKOTjCxbtXTDkFeFZAgMBAAECggEAQ1MxHvUONblh+VjljemAvyWc7JwOrADsBO4J3vwHEoAHqQKMb5SbkgVFrtGjYdYiZqjvDi3rGw0ZXHo12tvV1m8FgS0/ulDV4GxbYZ4YamnUErFF0licYFOGOIHTAKQpw+SC1lWKOL+vgsLMrIu0XsWgLMqMzG7wS08QvFOujNiap3oyE/uYxTrNLLu8XdkKdq4wtxbCaivgzrX9iu/PXmB4yVjtE78Fb3jfYy4VxKvrQQpnrTumP5GPXcBTz0Bpd9eXE9bczb6H67mMPqIaIovGJE6sR0R0NIy2H9RhK13rj2lE3bfq5jlj9ZsfQrn/yov61Nyy48B7nTnk6G7VDQKBgQDIC7OCjkZVSx4yk0AQeLaT14b8kS2R0wBrwNSI9wABJ7iLJzTyEtSJc5W+uEy5pGRcH+HKrycdTKiUOO6nRRSJqeB4agLR1maax661pUCHzyzNGtkCRo6Z0Ppg3rdQpCkAqyYtwTfX0xVeX5ZPYq1aJlzbsM5OCFNH/WVNKaUMxwKBgQDKeaDgVjyl/ZsNYHAaDZYNmRT1FE9PJcbSHpDD1T8oCr7zbkZLRhHxGRhB+uQ1DdLcZhlwYedUjAzYXNoyt7MUBMEQ7/2cYFScXyGvfEL0nfkxq1/Vz6+RZiSiw9DgNwBnKFklI99z+tix2VgPyhUQKFJMwJ7hgE+V5WghivJA3wKBgQC0IoVEvOTsjTXmCN6ZdnnB60QsTnagZ0ZrwTohE3o3kBMHiwiMKxSjqSdglAjS6gtNQZBKuSoZohvzTMjqarQxunzdMWjUl6HRIppaCzJumMoY72IWQH7MV3f+ns6nmQsrBPLeJK0qdXM6hgyN86dyFDVtxmofrjOAEdeUgjmTpQKBgGynYoagoIEvG+LMyrugaNK5QH7YPEsr6Yrebi85I2A4jAoUNlK0snIgVl0p5wb1eR9fBu3BDCPZ2BbPlSQ8YjQu7PBK6VzecOlNP8VtOH0OvShDX/VcM0oidyyFSnTX7zZsd5Ivsv0JMvoVuWUXu7/k821OvLQkaBD3f67oYmIfAoGBAIoKSb9f37hYW+uXWKFDBjx9C3zs6qSqpgdIlVXbs1lSFvbbRTmWviAXHo44B/qRE1EB50Cuo4kyNR9j+j5eK61S9A2zsTxsngXqIlY+mvhv35qVosiItWKYGR34ba38vhyq3kOJ+zc6+tDPlHZyTbjLB7HKGssxj2u9z/xk26gN}

# SuperAdmin Provisioning
super-admin:
  username: ${SUPER_ADMIN_USERNAME:admin}
  password: ${SUPER_ADMIN_PASSWORD:admin@lekhai.in}
  name: ${SUPER_ADMIN_NAME:default_superadmin}