# Flyway Configuration
flyway.url=jdbc:postgresql://localhost:5434/lekhai
flyway.user=postgres
flyway.password=postgres
flyway.locations=filesystem:src/main/resources/db/migration
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.validateOnMigrate=true
