# Flyway Configuration
flyway.url=jdbc:postgresql://ep-curly-king-a1k58bcv-pooler.ap-southeast-1.aws.neon.tech/neondb
flyway.user=neondb_owner
flyway.password=npg_4T6EDcxSzogY
flyway.locations=filesystem:src/main/resources/db/migration
flyway.baselineOnMigrate=true
flyway.baselineVersion=0
flyway.validateOnMigrate=true
